name: Run tests and upload coverage

on: 
  push

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.26'
          - '1.20'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt ./... # todo add -count=5 back after consistency issue is fixed with fallback tests on linux and go1.26

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: GO
        env:
          GO: ${{ matrix.go }}
